feat: add ensure-custom-hooks-using-other-hooks
eslint-react/eslint-react pull request #17
Opened 2023-10-25 10:35 UTC by hyoban

fix #1

2023-10-25 20:01 UTC, Rel1cx commented
Glad to see you're trying to implement this, but I need to be sure of the proper way to do it first, and when I'm done with debug/hooks, I'll see if we should use.

2023-10-25 23:18 UTC, hyoban commented
I will check and learn from that PR first.

2023-10-26 00:29 UTC, Rel1cx commented
> I will check and learn from that PR first.

Minor updates, see https://github.com/eslint-react/eslint-react/commit/8cd3f526503f1f9bf8b86a615dc74b20a5810f7c

2023-10-26 08:10 UTC, Rel1cx requested changes

2023-10-26 08:10 UTC, Rel1cx commented on packages/eslint-plugin-hooks/src/rules/ensure-custom-hooks-using-other-hooks.md
Add further reading at the end of the document to guide user to these two

[react.dev: invalid-hook-call-warning (the first note)](https://react.dev/warnings/invalid-hook-call-warning)
[react.dev: should-all-functions-called-during-rendering-start-with-the-use-prefix (the deep dive)](https://react.dev/learn/reusing-logic-with-custom-hooks#should-all-functions-called-during-rendering-start-with-the-use-prefix)

2023-10-26 08:34 UTC, Rel1cx approved these changes

2023-10-26 18:32 UTC, Rel1cx commented
I've updated the hooks-collector implementation to support more complex cases, such as nested hooks.

2023-10-27 03:26 UTC, merged